### PR TITLE
Added a tooltip on all disabled tools

### PR DESCRIPTION
**Pull request by fangedhex**
Hello :)
I made a small addition, I added tooltips on tools, swords... that are changed by this mod.
I wanted to avoid to say to all users that use my modpack that those tools doesn't work so I modified your mod and I want to share with you my modification so you can add it :D

It should work with all mods : I tested with Embers & Botania and it works !

PS : If you want me to modify something, don't hesitate ! :3
EDIT 1 : I saw some weird indent that I don't have on my local copy but it compiles and works.

### CODE REVIEW

**Comment by mainrs** [comment]
I will check it out when I am home! 
Thanks for the PR. You are actually the first person who created one for any of my projects. Makes me happy to see that people are using the mod :D

**Comment by mainrs** [comment]
Did you test the mod yourself on 1.10.2 and 1.11.2?

**Comment by fangedhex** [comment]
I tested it on 1.11.2 only because I'm making a modpack on that version but I wanted to share my modification of your mods so everybody can use it :P

EDIT : If you are happy with my work, I can try to add translation to your mod so we can have it in english, french(my native language) and maybe other if someone want to translate it !

**Review by mainrs — CHANGES_REQUESTED** [review]
Please bumb version in `mcmod.info` and gradle.properties file up to `1.0.6`.
**Edit:** I tested it on 1.10.2 and it works. After bumbping the version number I'll merge :smile:

**Comment by fangedhex** [comment]
I did what you asked for. Nothing has changed in "my" file, I just fixed the indenting and added some comment.

EDIT : Thanks for the merging :)

**Comment by mainrs** [comment]
Already merged ^^

**Comment by mainrs** [comment]
@FangedHex FYI I uploaded it to curse forge too! 

Out of curiosity, would you be interested in porting Growthcraft to 1.10/1.11?
I talked to both of the guys who are currently within the GrowthcraftCE organization. They told me they hadn't any time left for modding for now so I just thought why not trying it, right? 

I already ported apples, the core and the bamboo module. The bigger ones are still left though. It shouldn't be that hard. They managed to get most of it working for 1.8. So blockstates and stuff like that are mostly working. It's just method calls/refactoring that needs to be done. I decided to keep some ideas of the mods but mostly ditch the api and take a look if I can get a cleaner one going. 

No reason to hesitate if you are not interested :D but colaborating with others is always more fun ;)

**Comment by fangedhex** [comment]
I can try. My modification on your mod was my first time when doing modding on minecraft so it will take times to find some stuff, but there is some documentation on the internet so it's possible :)

**Comment by mainrs** [comment]
It's actually my first time I do anything with mods too! 
It's easy to find code samples because there are plenty of mods already working on newer versions of MC.

**Pull request merged**
