### PR TITLE
Ported to 1.12

### PR DESCRIPTION
**Pull request by fangedhex**
So I ported the mod to 1.12.
I created my own branch 1.12 but I can't ask to create a new one on your repository :(

Also I updated to Gradle 3.5...

### CODE REVIEW

**Comment by mainrs** [comment]
Did you make sure that it also runs on 1.10 and 1.11? I can merge it if you can say that for sure :smile:
Sorry, I had little time left for coding and other stuff. Some shit happened irl and I had to take care of it first. Hopefully I am gettign back to it :smile:

**Comment by fangedhex** [comment]
The main problem isn't not working for 1.10 and 1.11 cause there is no more CompatLayer for 1.12. I did make a branch named 1.12 but I can't merge request to you on a new branch :/

EDIT : I don't have some much times myself too but porting was easy...
EDIT 2 : Also, if you want, you can add me as a developper on your own repository ! :)

**Comment by fangedhex** [comment]
You need to add me on Curse & here as contributor so I can directly push updates if needed :)

**Comment by mainrs** [comment]
Ah sorry, I had a lot of stuff to do lately. Gimme a minute, I'll add you ^^
**Edit:** Mind merging into a completely new branch called 1.12? Nevermind, apparently I did it :D
You can now push to 1.12 freely.

**Pull request merged**
